//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblBook
    {
        public int BookId { get; set; }
        [Required(ErrorMessage = "Tên sách không được trống")]

        [DisplayName("Tên sách")]
        public string BookTitle { get; set; }
        [Required(ErrorMessage = "Chọn thể loại")]
        [DisplayName("Thể loại")]
        public string BookCategory { get; set; }
        [Required(ErrorMessage = "Hãy chọn số lượng)")]
        [DisplayName("Số lượng")]
        public Nullable<int> BookCopies { get; set; }
        [Required(ErrorMessage = "Tác giả không được trống")]
        [DisplayName("Tác giả")]
        public string BookAuthor { get; set; }
        [Range(1900, 2020)]
        [DisplayName("Năm xuất bản")]
        [Required(ErrorMessage = "Hãy chọn năm xuất bản")]
        public Nullable<int> Copyright { get; set; }
        [Required(ErrorMessage = "Chọn ngày thêm")]
        [DisplayName("Ngày thêm")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]

        public string DateAdded { get; set; }
        [Required(ErrorMessage = "Chọn trạng thái")]
        [DisplayName("Trạng thái")]
        public string Statuss { get; set; }
        [Required(ErrorMessage = "Chọn hình ảnh")]
        [DisplayName("Hình ảnh")]
        public string Images { get; set; }
        [Required(ErrorMessage = "Mô tả ngắn không được trống")]
        [DisplayName("Mô tả ngắn")]
        public string Descrip { get; set; }
        [DisplayName("Chương I")]
        [Required(ErrorMessage = "Chương không được trống !")]

        public string Images1 { get; set; }
        [DisplayName("Chương II")]
        [Required(ErrorMessage = "Chương không được trống !")]

        public string Images2 { get; set; }

        [DisplayName("Chương III")]
        [Required(ErrorMessage = "Chương không được trống !")]

        public string Images3 { get; set; }
        [Required(ErrorMessage = "Mô tả chi tiết không được trống")]
        [DisplayName("Mô tả chi tiết")]
        public string Detail { get; set; }
        //[System.Configuration.ConfigurationProperty("maxJsonLength", DefaultValue = 102400)]
        //public int MaxJsonLength { get; set; }
    }
}
