//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        public int UserId { get; set; }
        [DisplayName("Tên người dùng")]
        [Required(ErrorMessage = "Tên người dùng không được trống")]
        public string UserName { get; set; }
        [DisplayName("Giới tính")]
        [Required(ErrorMessage = "Hãy chọn giới tính !!")]


        public string UserGender { get; set; }
        [DisplayName("Email người dùng")]
        [Required(ErrorMessage = "Email không được trống !!")]



        public string UserEmail { get; set; }
        [DisplayName("Mật khẫu")]
        [Required(ErrorMessage = "Mật khẩu không được trống !!")]


        public string UserPass { get; set; }
    }
}
